name: Deploy to Cloudflare (Multi Akun)

on:
  workflow_dispatch:
    inputs:
      account_id:
        description: "Cloudflare Account ID"
        required: true
      api_token:
        description: "Cloudflare API Token"
        required: true
      domain_prefix:
        description: "Prefix domain (contoh: siren.afrcloud.site)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Generate wrangler.toml dynamically
      run: |
        echo "Membuat wrangler.toml dari input..."

        # Bagian statis
        echo "name = \"vl\"" > wrangler.toml
        echo "main = \"worker.js\"" >> wrangler.toml
        echo "compatibility_date = \"2024-05-23\"" >> wrangler.toml

        # Bagian dinamis berdasarkan input
        echo "account_id = \"${{ github.event.inputs.account_id }}\"" >> wrangler.toml
        echo "workers_dev = true" >> wrangler.toml

        # Routes yang disesuaikan dengan domain prefix
        echo "routes = [" >> wrangler.toml
        for domain in "siren" "support.zoom.us" "ava.game.naver.com" "graph.instagram.com" "df.game.naver.com" "quiz.int.vidio.com" "zoomgov.com" "api24-normal-alisg.tiktokv.com" "zaintest.vuclip.com" "help.viu.com" "grabacademyportal.grab.com" "api22-normal-c-alisg.tiktokv.com" "live.iflix.com" "store.linefriends.com" "cache.netflix.com" "customlinks.appsflyer.com"; do
          echo "  { pattern = \"$domain.\${{ github.event.inputs.domain_prefix }}\", custom_domain = true }," >> wrangler.toml
        done
        echo "]" >> wrangler.toml

        echo "wrangler.toml berhasil dibuat:"
        cat wrangler.toml

    - name: Deploy ke Cloudflare Workers
      run: wrangler publish
      env:
        CLOUDFLARE_API_TOKEN: ${{ github.event.inputs.api_token }}
