name: Deploy to Cloudflare (Multi Akun)

on:
  workflow_dispatch:
    inputs:
      account_id:
        description: "Cloudflare Account ID"
        required: true
      api_token:
        description: "Cloudflare API Token"
        required: true
      domain_prefix:
        description: "Prefix domain (contoh: siren.afrcloud.site)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Generate wrangler.toml dynamically
      run: |
        echo "Membuat wrangler.toml dari input..."

        cat <<EOF > wrangler.toml
name = "vl"
main = "worker.js"
compatibility_date = "2024-05-23"

account_id = "${{ github.event.inputs.account_id }}"
workers_dev = true

routes = [
  { pattern = "siren.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "support.zoom.us.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "ava.game.naver.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "graph.instagram.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "df.game.naver.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "quiz.int.vidio.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "zoomgov.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "api24-normal-alisg.tiktokv.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "zaintest.vuclip.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "help.viu.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "grabacademyportal.grab.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "api22-normal-c-alisg.tiktokv.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "live.iflix.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "store.linefriends.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "cache.netflix.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true },
  { pattern = "customlinks.appsflyer.com.${{ github.event.inputs.domain_prefix }}", custom_domain = true }
]
EOF

        echo "wrangler.toml berhasil dibuat:"
        cat wrangler.toml

    - name: Deploy ke Cloudflare Workers
      run: wrangler publish
      env:
        CLOUDFLARE_API_TOKEN: ${{ github.event.inputs.api_token }}
