name: Deploy Worker to Cloudflare

on:
  workflow_dispatch:
    inputs:
      worker_name:
        description: 'Nama Worker'
        required: true
        type: string
      cloudflare_account_id:
        description: 'Cloudflare Account ID'
        required: true
        type: string
      cloudflare_api_token:
        description: 'Cloudflare API Token'
        required: true
        type: string
      main_domain:
        description: 'Main domain for the worker (e.g., nzr2805.my.id)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Membuat package.json jika tidak ada
        id: check_package_json
        run: |
          if [ ! -f "package.json" ]; then
            echo "File package.json tidak ditemukan, membuat file baru..."
            npm init -y
            npm install wrangler@latest
          else
            echo "File package.json sudah ada."
          fi
          
      - name: Dynamic Wrangler.toml
  run: |
    echo "name = \"${{ inputs.worker_name }}\"" > wrangler.toml
    echo "main = \"worker.js\"" >> wrangler.toml
    echo "compatibility_date = \"2024-05-23\"" >> wrangler.toml
    echo "workers_dev = true" >> wrangler.toml
    echo "" >> wrangler.toml
    echo "routes = [" >> wrangler.toml
    echo "  { pattern = \"${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"add.customlinks.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"api.midtrans.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"api22-normal-c-alisg.tiktokv.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"api24-normal-alisg.tiktokv.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"api24-normal-tiktokv.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"api24-normal-useast1a.tiktokv.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"app-stg.gopay.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"app.gopay.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"app.midtrans.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"ava.game.naver.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"bimbel.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"blog.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"blog.webex.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"cache.netflix.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"cdn.customlinks.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"cf.shopee.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"collection.linefriends.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"creativeservices.netflix.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"customlinks.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"dashboard.midtrans.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"dev.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"df.game.naver.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"edu.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"go.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"go.medallia.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"grabalumni.grab.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"grabacademyportal.grab.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"graph.instagram.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"gw.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"help.viu.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"hurricane.lipcon.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"img.email1.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"img.email2.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"img.email3.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"info.udemy.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"investor.fb.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"investor.medallia.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"io.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"live.iflix.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"nontontv.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"npca.netflix.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"quiz.int.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"quiz.staging.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"quiz.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"roboguru.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"s.lazada.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"s.shopee.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"space.byu.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"store.linefriends.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"support.zoom.us.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"www.lipcon.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"www.midtrans.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"www.udemy.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"zaintest.vuclip.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"zoomgov.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
    echo "  { pattern = \"zoomgov.com.${{ inputs.main_domain }}\", custom_domain = true }" >> wrangler.toml
    echo "]" >> wrangler.toml
    
      - name: Dynamic Wrangler.toml
        run: |
          echo "name = \"${{ inputs.worker_name }}\"" > wrangler.toml
          echo "main = \"worker.js\"" >> wrangler.toml
          echo "compatibility_date = \"2024-05-23\"" >> wrangler.toml
          echo "workers_dev = true" >> wrangler.toml
          echo "" >> wrangler.toml
          echo "routes = [" >> wrangler.toml
          echo "  { pattern = \"${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"add.customlinks.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"api.midtrans.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"api22-normal-c-alisg.tiktokv.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"api24-normal-alisg.tiktokv.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"api24-normal-tiktokv.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"api24-normal-useast1a.tiktokv.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"app-stg.gopay.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"app.gopay.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"app.midtrans.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"ava.game.naver.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"bimbel.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"blog.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"blog.webex.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"cache.netflix.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"cdn.customlinks.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"cf.shopee.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"collection.linefriends.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"creativeservices.netflix.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"customlinks.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"dashboard.midtrans.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"dev.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"df.game.naver.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"edu.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"go.appsflyer.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"go.medallia.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"grabalumni.grab.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"grabacademyportal.grab.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"graph.instagram.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"gw.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"help.viu.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"hurricane.lipcon.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"img.email1.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"img.email2.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"img.email3.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"info.udemy.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"investor.fb.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"investor.medallia.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"io.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"live.iflix.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"nontontv.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"npca.netflix.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"quiz.int.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"quiz.staging.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"quiz.vidio.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"roboguru.ruangguru.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"s.lazada.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"s.shopee.co.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"space.byu.id.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"store.linefriends.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"support.zoom.us.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"www.lipcon.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"www.midtrans.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"www.udemy.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"zaintest.vuclip.com.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"zoomgov.${{ inputs.main_domain }}\", custom_domain = true }," >> wrangler.toml
          echo "  { pattern = \"zoomgov.com.${{ inputs.main_domain }}\", custom_domain = true }" >> wrangler.toml
          echo "]" >> wrangler.toml

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ inputs.cloudflare_api_token }}
          accountId: ${{ inputs.cloudflare_account_id }}
